name: Test CI

on:
  push:
    paths:
      - 'app'
      - 'azure.yml'
      - '.github/workflows/test_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12, 14, 16]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test

